name: 发布 Windows 版本

on:
  push:
    tags:
      - 'v*.*.*' # 触发条件：当一个形如 v1.0.0 的标签被推送时

jobs:
  build-windows:
    runs-on: windows-latest # 只在 Windows 上运行

    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 设置 Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: 安装依赖
        run: npm install

      - name: 构建应用
        run: npm run build -- --win
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 上传构建产物
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: dist/*.exe
          retention-days: 5
          compression-level: 9 # 最高压缩级别，减小文件大小
          overwrite: true # 如果存在同名构建产物则覆盖

      - name: 创建发布并上传资源
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            dist/*.exe
            dist/*.zip
          name: 屏幕录制工具 ${{ github.ref_name }}
          body: |
            ## 屏幕录制工具 Windows 版本 ${{ github.ref_name }}

            ### 安装方法
            下载并运行 .exe 安装文件

            ### 更新内容
            - 自动构建的 Windows 版本
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
